/**
 * @mcpapps/typegen — generate typed Dart models from zod tool schemas, via
 * JSON Schema as the language-neutral interchange format.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { z } from "zod";
import { type JsonSchemaLike, jsonSchemaToDart } from "./json-schema-to-dart.js";

export { type JsonSchemaLike, jsonSchemaToDart } from "./json-schema-to-dart.js";

export interface DartModelSpec {
  /** Generated Dart class name, e.g. "GetWeatherOutput". */
  name: string;
  /** The zod schema to translate (typically a tool's output schema). */
  schema: z.ZodTypeAny;
}

const DART_HEADER = [
  "// AUTO-GENERATED by @mcpapps/typegen. Do not edit by hand.",
  "// ignore_for_file: prefer_const_constructors, unnecessary_this, non_constant_identifier_names",
].join("\n");

/** Generate Dart source (header + one class tree per spec) from zod schemas. */
export function zodToDart(specs: DartModelSpec[]): string {
  const blocks = specs.map((spec) => {
    const json = spec.schema.toJSONSchema() as JsonSchemaLike;
    return jsonSchemaToDart(spec.name, json);
  });
  return `${[DART_HEADER, ...blocks].join("\n\n")}\n`;
}

/** Generate Dart models and write them to `outFile`. */
export async function writeDartModels(specs: DartModelSpec[], outFile: string): Promise<void> {
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, zodToDart(specs));
}
