import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildFlutterComponent, slug } from "@mcpapps/flutter";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const COMPONENT_URI = "ui://weather-flutter/get_weather";

console.log("Building inlined Flutter component for deploy…");
const component = await buildFlutterComponent({
  projectDir: resolve(root, "flutter"),
  uri: COMPONENT_URI,
  inline: true,
});

// The self-contained HTML is multi-MB (CanvasKit + Dart) — too large for the
// Worker script bundle. Write it as a Cloudflare static asset; the Worker reads
// it via the ASSETS binding on `resources/read` (see @mcpapps/server mountMcp).
const assetPath = `/_c/${slug(COMPONENT_URI)}/index.html`;
const dist = resolve(root, "dist");
await rm(dist, { recursive: true, force: true });
const dest = join(dist, assetPath.replace(/^\//, ""));
await mkdir(dirname(dest), { recursive: true });
await writeFile(dest, component.html);
console.log(`✓ wrote ${(component.html.length / 1024 / 1024).toFixed(1)}MB → dist${assetPath}`);

const metaDir = resolve(here, "generated");
await mkdir(metaDir, { recursive: true });
await writeFile(
  join(metaDir, "component-meta.ts"),
  [
    "// Auto-generated by src/pre-deploy.ts — do not edit",
    `export const COMPONENT_URI = ${JSON.stringify(COMPONENT_URI)};`,
    `export const COMPONENT_HTML_ASSET = ${JSON.stringify(assetPath)};`,
    `export const COMPONENT_CSP = ${JSON.stringify(component.csp ?? {})};`,
    "",
  ].join("\n"),
);
console.log("✓ wrote src/generated/component-meta.ts");
