import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildFlutterComponent } from "@mcpapps/flutter";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const COMPONENT_URI = "ui://weather-flutter/get_weather";

console.log("Building Flutter component for deploy…");
const component = await buildFlutterComponent({
  projectDir: resolve(root, "flutter"),
  uri: COMPONENT_URI,
});

// Write assets into dist/ nested under the basePath so Cloudflare Static Assets
// serves them at the correct URLs (e.g. /_c/weather-flutter-get-weather/).
const pathSegments = (component.basePath ?? "").replace(/^\/|\/$/g, "").split("/");
const distBase = resolve(root, "dist", ...pathSegments);
await mkdir(distBase, { recursive: true });
for (const [rel, asset] of Object.entries(component.assets ?? {})) {
  const dest = join(distBase, rel);
  await mkdir(dirname(dest), { recursive: true });
  await writeFile(dest, asset.body);
}
console.log(`✓ wrote ${Object.keys(component.assets ?? {}).length} assets → dist/`);

// Write component metadata for the Worker to import at bundle time.
const metaDir = resolve(here, "generated");
await mkdir(metaDir, { recursive: true });
await writeFile(
  join(metaDir, "component-meta.ts"),
  [
    "// Auto-generated by src/pre-deploy.ts — do not edit",
    `export const COMPONENT_URI = ${JSON.stringify(COMPONENT_URI)};`,
    `export const COMPONENT_HTML = ${JSON.stringify(component.html)};`,
    `export const COMPONENT_BASE_PATH = ${JSON.stringify(component.basePath)};`,
    "",
  ].join("\n"),
);
console.log("✓ wrote src/generated/component-meta.ts");
