import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type {
  CompiledComponent,
  McpUiPermissions,
  McpUiResourceCsp,
  UiResourceUri,
} from "@mcpapps/protocol";
import vue from "@vitejs/plugin-vue";
import { build, type Plugin, type Rollup } from "vite";
import { renderComponentHtml } from "./html.js";

const ENTRY_ID = "virtual:mcpapp-entry";
const RESOLVED_ENTRY_ID = `\0${ENTRY_ID}`;

/** Virtual entry that imports the component and boots it via the Vue adapter. */
function entryPlugin(componentPath: string): Plugin {
  return {
    name: "mcpapps:vue-entry",
    resolveId(id) {
      return id === ENTRY_ID ? RESOLVED_ENTRY_ID : undefined;
    },
    load(id) {
      if (id !== RESOLVED_ENTRY_ID) return undefined;
      return [
        `import { mountApp } from "@mcpapps/client-core";`,
        `import { createVueAdapter } from "@mcpapps/vue";`,
        `import Component from ${JSON.stringify(componentPath)};`,
        `mountApp(createVueAdapter(Component));`,
      ].join("\n");
    },
  };
}

/** CSP/permissions/appearance hints emitted into the component's `_meta.ui`. */
export interface ComponentAppearance {
  csp?: McpUiResourceCsp;
  permissions?: McpUiPermissions;
  domain?: string;
  prefersBorder?: boolean;
}

export interface BuildVueComponentOptions extends ComponentAppearance {
  /** Absolute path to the `.vue` entry component. */
  entry: string;
  /** The `ui://` URI this component is served at. */
  uri: UiResourceUri;
  /** Project root used to resolve dependencies. Default `process.cwd()`. */
  root?: string;
  /** Minify the bundle. Default true. */
  minify?: boolean;
  /** Document title. */
  title?: string;
}

/**
 * Compile a Vue SFC into a single self-contained `ui://` HTML resource. Vue,
 * the component, the client-core runtime and the adapter are all bundled and
 * inlined, so the resulting HTML has no external dependencies.
 */
export async function buildVueComponent(
  opts: BuildVueComponentOptions,
): Promise<CompiledComponent> {
  const result = await build({
    root: opts.root ?? process.cwd(),
    configFile: false,
    logLevel: "silent",
    plugins: [vue(), entryPlugin(opts.entry)],
    build: {
      write: false,
      cssCodeSplit: false,
      minify: opts.minify ?? true,
      rollupOptions: {
        input: ENTRY_ID,
        output: {
          format: "iife",
          name: "McpAppComponent",
          inlineDynamicImports: true,
        },
      },
    },
  });

  const output = extractOutput(result);
  let js = "";
  let css = "";
  for (const chunk of output) {
    if (chunk.type === "chunk" && chunk.isEntry) {
      js = chunk.code;
    } else if (chunk.type === "asset" && chunk.fileName.endsWith(".css")) {
      css += typeof chunk.source === "string" ? chunk.source : Buffer.from(chunk.source).toString();
    }
  }
  if (!js) throw new Error(`buildVueComponent produced no JS for ${opts.entry}`);

  const html = renderComponentHtml({ js, css, ...(opts.title ? { title: opts.title } : {}) });
  const component: CompiledComponent = { uri: opts.uri, html };
  if (opts.csp) component.csp = opts.csp;
  if (opts.permissions) component.permissions = opts.permissions;
  if (opts.domain) component.domain = opts.domain;
  if (opts.prefersBorder !== undefined) component.prefersBorder = opts.prefersBorder;
  return component;
}

export interface ComponentSpec extends ComponentAppearance {
  /** Export name in the generated module (use a valid JS identifier). */
  name: string;
  entry: string;
  uri: UiResourceUri;
  title?: string;
}

/**
 * Build several components and write them to a generated TS module exporting one
 * `CompiledComponent` per spec — the server imports this at build time.
 */
export async function writeComponentsModule(
  specs: ComponentSpec[],
  outFile: string,
  options: { root?: string; minify?: boolean } = {},
): Promise<CompiledComponent[]> {
  const built: { name: string; component: CompiledComponent }[] = [];
  for (const spec of specs) {
    const component = await buildVueComponent({
      entry: spec.entry,
      uri: spec.uri,
      ...(options.root ? { root: options.root } : {}),
      ...(options.minify !== undefined ? { minify: options.minify } : {}),
      ...(spec.title ? { title: spec.title } : {}),
      ...(spec.csp ? { csp: spec.csp } : {}),
      ...(spec.permissions ? { permissions: spec.permissions } : {}),
      ...(spec.domain ? { domain: spec.domain } : {}),
      ...(spec.prefersBorder !== undefined ? { prefersBorder: spec.prefersBorder } : {}),
    });
    built.push({ name: spec.name, component });
  }

  const lines = [
    "// AUTO-GENERATED by @mcpapps/vite-plugin-vue. Do not edit by hand.",
    'import type { CompiledComponent } from "@mcpapps/protocol";',
    "",
    ...built.map(
      (b) => `export const ${b.name}: CompiledComponent = ${JSON.stringify(b.component)};`,
    ),
    "",
  ];
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, lines.join("\n"));
  return built.map((b) => b.component);
}

function extractOutput(
  result: Awaited<ReturnType<typeof build>>,
): Rollup.OutputChunk[] | Rollup.OutputAsset[] | (Rollup.OutputChunk | Rollup.OutputAsset)[] {
  if (Array.isArray(result)) {
    return result.flatMap((r) => r.output);
  }
  if ("output" in result) {
    return result.output as (Rollup.OutputChunk | Rollup.OutputAsset)[];
  }
  throw new Error("Unexpected Vite build result (watch mode is not supported).");
}
